name: "Build_Test_Deploy"

on:
  workflow_dispatch:
  # Just run it

  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "**/README.md"
  push:
    branches: [main, develop]
    tags:
      - "v*"
    paths-ignore:
      - "**/README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  EVM_DEPLOYER: ${{ secrets.EVM_DEPLOYER }}
jobs:
  build-test-deploy:
    uses: ./.github/workflows/build-test.yml
    secrets:
      EVM_DEPLOYER: ${{ secrets.EVM_DEPLOYER }}
      GH_PKG_LOGIN: ${{ secrets.GH_PKG_LOGIN }}
      GH_PKG_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
